name: React App CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install
        working-directory: Dia 2

      - name: Rodar testes
        run: npm test -- --watchAll=false --roots "./src"
        working-directory: Dia 2

      - name: Build do projeto
        run: npm run build
        working-directory: Dia 2
